name: "Continuous Build"

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        test-java-version:
          - 8
          - 11
          - 17
          - 21
        protobuf-version:
          - '' # Use from source code
        include:
          - os: ubuntu-latest
            test-java-version: 21
            protobuf-version: 3.18.0
          - os: ubuntu-latest
            test-java-version: 21
            coverage: true
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: setup-java-8
        name: Setup Java 8 for tests
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 8
          java-package: jre
      - id: setup-java-11
        name: Setup Java 11 for tests
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11
      - id: setup-java-21
        name: Setup Java 21
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 21
      - id: setup-java-17
        name: Setup Java 17
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
      - uses: gradle/actions/setup-gradle@v4
      - name: Run Tests
        run: |
          ./gradlew build ${{ matrix.coverage && 'jacocoTestReport' || '' }} -PtestJavaVersion=${{ matrix.test-java-version }} -Porg.gradle.java.installations.paths="${{ steps.setup-java-8.outputs.path }},${{ steps.setup-java-11.outputs.path }},${{ steps.setup-java-17.outputs.path }},${{ steps.setup-java-21.outputs.path }}"
        env:
          PROTOBUF_VERSION: ${{ matrix.protobuf-version }}
      - uses: codecov/codecov-action@v2.1.0
        if: ${{ matrix.coverage }}
  publish-snapshots:
    name: Publish snapshots
    if: ${{ github.event_name == 'push' && github.repository == 'curioswitch/protobuf-jackson' }}
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Java 17
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
      - uses: gradle/actions/setup-gradle@v4
      - run: ./gradlew snapshot
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          MAVEN_GPG_PRIVATE_KEY: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          MAVEN_GPG_PUBLIC_KEY: ${{ secrets.MAVEN_GPG_PUBLIC_KEY }}
